### ISSUE TITLE
Golang package gone?

### ISSUE THREAD

**Issue by arnlen** [tgogos/goprocinfo_test#1]
I find this repo after reading your post on [stackoverflow](https://stackoverflow.com/a/42006705/1590419): very nice work! 👏 
I'm trying to accomplish exactly the same think you were doing to monitor my Raspberry Pi 4.
Is you Go packing still available somewhere?

Thanks a lot. 😃

**Comment by tgogos** [comment]
Hey @arnlen thanks for your kind words!
Everything I needed to take the actual measurements (back then) is in this repo, nothing is missing. I just wrote simple `.go` programs to periodically read the data from `/proc/stat` and `/proc/meminfo` pseudo-files, which is the "linux" place to go and look for such kind of information.

As the `README` says, I used a library called [goprocinfo](https://github.com/c9s/goprocinfo) to do the parsing for me and then, after getting the values, I did a few simple calculations. I actually made a post on Stackoverflow on how `htop` is doing it and got back a response from the `htop` author 😃 (more here: [How to calculate system memory usage from /proc/meminfo (like htop)](https://stackoverflow.com/questions/41224738/how-to-calculate-system-memory-usage-from-proc-meminfo-like-htop))

I really don't know the evolution of [goprocinfo](https://github.com/c9s/goprocinfo) and if it can still be used nowadays, but if I had to implement it again today, I would definitely take a look to [prometheus/procfs](https://pkg.go.dev/github.com/prometheus/procfs).

Let me know if this helps...
